config/routes.rb
Rails.application.routes.draw do

  root 'profiles#show'
  get '/register' => 'profiles#new'
  post '/register' => 'profiles#show'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # get '/user_form' => 'users#update'
  post '/user_form/:id' => 'users#ajax'
  get '/new_form/:id' => 'users#edit'
  get '/profiles/:id/del' => 'profiles#delivery'
  get '/profiles/:id/orders' => 'profiles#invoice'
  resources :users
  # post '/add_address' => 'profiles#address'

  resources :profiles do
    member do
      get :confirm_email
      put :hold
      get :delivery
      get :invoice
    end

    resources :users
    resources :charges, only: [:create, :update] do
      collection do
        put :cancel
      end
    end
  end


  resources :sessions

end

app/models/profile.rb
class Profile < ApplicationRecord
  before_create :confirmation_token
  has_secure_password
  has_many :users
  has_many :orders, through: :users
  has_many :products, through: :orders

validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, uniqueness: true, confirmation: true, case_sensitive: false
# validates :password, confirmation: true, length: { minimum: 8 }


  # geocoded_by :address
    def address
      [address1, address2, city, state, zip].compact.join(', ')
    end

  def self.total_amount(id)
    profile = Profile.find(id)
    customer = Stripe::Customer.retrieve(profile.stripe_id)
    total = Stripe::Invoice.all(:customer => customer.id).data[0][:total] /100
    amount = "$ #{'%.2f' % total}"
  end

  def self.delivery_day(delivery)
    delivery.strftime('%d').to_i.ordinalize
  end

  def self.invoice_date(id)
    profile = Profile.find(id)
    customer = Stripe::Customer.retrieve(profile.stripe_id)
    date = Time.at(Stripe::Invoice.all(:customer => customer.id).data[0][:date])
    date.strftime('%D')
  end

  def self.status(id)
    profile = Profile.find(id)
    customer = Stripe::Customer.retrieve(profile.stripe_id)
    status = Stripe::Invoice.all(:customer => customer.id).data[0][:paid]
      if status == true
        return "paid"
      else
        return "processing"
      end
  end

  def self.boxes(id)
    profile = Profile.find(id)
    Profile.find(id).users.count
  end


  # def self.invoice_line(id)
  #   profile = Profile.find(id)
  #   customer = Stripe::Customer.retrieve(profile.stripe_id)
  #    invoice_id = Stripe::Invoice.all(:customer => customer.id).data[0][:id]
  #    charge_id = Stripe::Invoice.all(:customer => customer.id).data[0][:charge]
  #    Stripe::Invoice.retrieve(:customer => customer.id).lines.all({
  #   :limit => 5})
  # end

  private
    def confirmation_token
        if self.confirm_token.blank?
          self.confirm_token = SecureRandom.urlsafe_base64.to_s
        end
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authorize, except: [:create, :new]
  before_action :set_profile, only: [:show, :edit, :update, :destroy, :delivery, :hold, :invoice]
  # before_action :create_invoice, only: [:invoice]


  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @users = @profile.users.all
    if @users.blank? then
      @first=""
    else
      @first= @users.first.first_name
    end
    @user = User.new
    if request.xhr?
      render @profile
    end

  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json

    def create
      @profile = Profile.new(profile_params)

  # this section is the old way, the second section I added for email confirm, keep this section just in case we toss the other. #

        respond_to do |format|
        if @profile.save
          session[:profile_id] = @profile.id
          format.html { redirect_to profile_path(@profile), notice: 'Thanks for joining TOM!.' }
          format.json { render :show, status: :created, location: @profile }
        else
          format.html { redirect_to new_session_path, notice: 'Profile was not successfully created, please ensure to fill in all fields.' }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end

      # if @profile.save
      #   session[:profile_id] = @profile.id
      #   ProfileMailer.registration_confirmation(@profile).deliver
      #   flash[:notice] = "Please confirm your email address to continue"
      #   redirect_to profile_path(@profile)
      # else
      #   format.html { redirect_to new_session_path, notice: 'Profile was not successfully created, please ensure to fill in all fields.' }
      #   format.json { render json: @profile.errors, status: :unprocessable_entity }
      #   flash[:error] = "Ah ah ah.... try again."
      #   redirect_to new_session_path
      # end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    # if request.xhr?
    #   render 'delivery', layout: false
    # end

    respond_to do |format|
      if @profile.update(delivery_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delivery
    if request.xhr?
      render '_del', layout: false
    end
  end

def invoice
  if request.xhr?
    render '_orders', layout: false
  end
end

  def confirm_email
    profile = Profile.find_by_confirm_token(params[:id])
    if profile
      profile.email.active
      flash[:success] = "Welcome to TOM! Your email has been confirmed. Please sign in to continue."
      redirect_to '/login'
    else
      flash[:error] = "Sorry that profile does not exist."
      redirect_to @profile
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_in_params
      params.require(:profile).permit(:email, :password, :password_confirmation)
    end

    def stripe_params
      params.permit :stripeEmail, :stripeToken
    end

    def delivery_params
      params.require(:profile).permit(:address1, :address2, :city, :state, :zip, :delivery)
    end

    def profile_params
      params.require(:profile).permit(:email, :password, :password_confirmation, :address1, :address2, :city, :state, :zip, :delivery)
    end

    # def current_profile
    #   @_current_profile ||= session[:current_profile_id] &&
    #   Profile.find_by(id: session[:current_profile_id])
    # end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_del.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h5>Shipping Address</h5>
<br>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address1 %>
  </div>

  <div class="field">
    <%= f.label :apt %>
    <%= f.text_field :address2 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>
<img src="https://s3.amazonaws.com/tombox/calendar.png" alt="TomBox" height="50" width="50">
  <div class="field">
    <%= f.label :When_would_you_like_your_delivery_to_start? %>
    <%= f.date_field :delivery %>
  </div>

  <button style="z-index:0;"class="btn purple darken-1 waves-effect waves-light" type="submit" name="action">  <%= f.submit %>
  </button>
  </div>
<% end %>
<br>
<h5 id="billing">Billing</h5>
<p style="color:red;"> <em>Protecting your billing information is a priority for us. <br> We do not store your billing information on our server. <br>Payment is securely completed via STRIPE (PCI-DSS Compliant)<em></p>
<br>
<%= render 'charges/new' %>
<br>
<br>
<br>

app/views/profiles/_delivery.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address1 %>
  </div>

  <div class="field">
    <%= f.label :apt %>
    <%= f.text_field :address2 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :When_would_you_like_your_delivery_to_start? %>
    <%= f.date_field :delivery %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= render 'charges/new' %>
<br>
<%=link_to 'Cancel', @profile%>s

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_orders.html.erb
<div class="invoice_table">Invoice History</div>
<br>
<table class="responsive-table bordered">
		<tr>
			<th><strong>Date</strong></th>
			<th><strong>Amount</strong></th>
			<th><strong>Status</strong></th>
		</tr>
		<tr>
			<td><%= Profile.invoice_date(@profile.id) %></td>
			<td><%= Profile.total_amount(@profile.id) %></td>
			<td><%= Profile.status(@profile.id) %> </td>
		</tr>
	</table>
	<br>
	<br>
	<div class="invoice_table">Box Info </div>
	<br>
	<table class="responsive-table bordered">
	<tr>
			 <td><strong>Your monthly delivery day &nbsp;&nbsp;<%= Profile.delivery_day(@profile.delivery) %></strong> </td>
	</tr>
	<tr>
			<td><strong>Total Boxes ordered&nbsp;&nbsp;&nbsp;&nbsp;<%= Profile.boxes(@profile) %></strong></td>
	</tr>
	</table>
<br>
<br>
	<% if @profile.subscribed == nil %>
	<% elsif @profile.subscribed == true %>

  <%= link_to 'Cancel Your Subscription', cancel_profile_charges_path(@profile), method: :put, data: { confirm: 'Are you sure you want to cancel your Subscription?' } %>
	<% else %>
  <button class="btn purple darken-1 waves-effect waves-light" type="submit" name="action">   <%= link_to 'Re-Activate Subscription', delivery_profile_path(@profile), method: :get, data: { confirm: 'You need to enter your payment information' } %>
  </button>

	<%end %>

app/views/profiles/_show.html.erb
<button class="squatchpop">Referral Discount</button>

  <p class="dis_title">Your Profile </p>
   <table class="responsive-table bordered">
    <tbody>
      <tr>
        <td><strong>Email:</strong></td>
        <td><%= @profile.email %></td>
      </tr>
      <tr>
        <% unless @profile.address1.blank? %>
        <td><strong>Address1:</strong></td>
        <td><%= @profile.address1 %></td>
        <% end %>
      </tr>
      <tr>
        <% unless @profile.address2.blank? %>
        <td><strong>Address2:</strong></td>
        <td><%= @profile.address2 %></td>
        <% end %>
      </tr>
      <tr>
        <% unless @profile.city.blank? %>
        <td><strong>City:</strong></td>
        <td><%= @profile.city %></td>
         <% end %>
      </tr>
      <tr>
        <% unless @profile.state.blank? %>
        <td><strong>State:</strong></td>
        <td><%= @profile.state %></td>
        <% end %>
      </tr>
      <tr>
        <% unless @profile.zip.blank? %>
        <td><strong>Zip:</strong></td>
        <td><%= @profile.zip %></td>
        <% end %>
      </tr>
    </tbody>
  </table>

app/views/profiles/delivery.html.erb
<div class="banner" data-users="<%= @first %>"></div>
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="profile_container">
  <div class="side_panel">
    <ul class="navig" data-profile="<%= @profile.id %>">
      <div class="accordion" id="your_orders">Your Subscriptions</div>
      <% @profile.users.each do |user| %>
      <div class="panel" data-user="<%= user.id %>"><%= link_to user.first_name, profile_user_path(@profile, user) %></div>
      <% end %>
      <div class="side_links" id="new_user">New User</div>
      <div class="side_links"><%= link_to 'Delivery', delivery_profile_path(@profile) %></div>
      <div class="side_links">Refer someone</div>
      <!-- <div class="side_links">
      </div> -->
      <div class="side_links">
        <% if @profile.subscribed == nil %>
        <% else @profile.subscribed == true %>
          <%= link_to 'Order History', invoice_profile_path(@profile), method: :get %>
        <% end %>
      </div>
    </ul>
  </div>
<div class="main_panel">
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address1 %>
  </div>

  <div class="field">
    <%= f.label :apt %>
    <%= f.text_field :address2 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :When_would_you_like_your_delivery_to_start? %>
    <%= f.date_field :delivery %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= render 'charges/new' %>
<br>
<%=link_to 'Cancel', @profile%>
</div>

<!-- <%#= render 'charges/custom' %> -->

app/views/profiles/edit.html.erb
<h2>Update Your Profile</h2>

<%= render 'delivery', profile: @profile %>

<%= link_to 'Cancel', @profile %>

app/views/profiles/invoice.html.erb
<div class="paper z-depth-2">
	<div class="invoice_title">
		<h4> Subscription info </h4>
	</div>

	<div class="invoice_boxes">
		<h5> Boxes monthly deleivery day: <%= Profile.delivery_day(@profile.delivery) %> day of each month. </h5>
	</div>

	<div class="invoice_boxes"><h5> Boxes ordered: <%= Profile.boxes(@profile) %> </h5></div>

	<table class="responsive-table bordered"> 
	<h4>Order Invoices</h4>

		<tr>
			<th><h4> Date </h4> </th>
			<th><h4> Amount </h4></th>
			<th><h4> Status </h4> </th> 
		</tr>
		<tr>
			<td><%= Profile.invoice_date(@profile.id) %></td>
			<td><%= Profile.total_amount(@profile.id) %></td>
			<td><%= Profile.status(@profile.id) %> </td>
		</tr>
	</table>

	<br>
	<%= link_to 'Back', profile_path(@profile) %>
	<% if @profile.subscribed == nil %>
	<% elsif @profile.subscribed == true %>
	  | <%= link_to 'Cancel Your Subscription', cancel_profile_charges_path(@profile), method: :put, data: { confirm: 'Are you sure you want to cancel your Subscription?' } %>
	<% else %>
	  | <%= link_to 'Re-Activate Subscription', delivery_profile_path(@profile), method: :get, data: { confirm: 'You need to enter your payment information' } %>
	<%end %>
</div>

app/views/profiles/show.html.erb
<% if flash[:just_signed_up] %>
<p class="welcome">Thanks for joining TOM!</p>
<% end %>

<div class="banner" data-users="<%= @first %>"></div>

<div class="profile_container">
  <div class="side_panel">
    <ul class="navig" data-profile="<%= @profile.id %>">
      <div class="accordion" id="your_orders">Your Subscriptions</div>
      <% @profile.users.each do |user| %>
      <div class="panel" id='user_profile' data-user="<%= user.id %>"><%= link_to user.first_name, profile_user_path(profile_id:@profile.id,id: user.id) %> </div>
      <% end %>
      <div class="side_links pointer" id="new_user">Add a Box</div>
      <div class="side_links pointer" id="delivery">Shipping &amp; Billing</div>
      <div class="side_links pointer" id="refer">Referral Code</div>
      <% if @profile.subscribed == nil %>
      <% else @profile.subscribed == true %>
      <div class="side_links pointer" id="invoice">Order History</div>
      <% end %>
    </ul>
  </div>
<div class="main_panel">
  <p class="dis_title">Your Profile</p>
   <table class="responsive-table bordered">
    <tbody>
      <tr>
        <td><strong>Email:</strong></td>
        <td><%= @profile.email %></td>
      </tr>
      <tr>
        <% unless @profile.address1.blank? %>
        <td><strong>Address:</strong></td>
        <td><%= @profile.address1 %></td>
        <% end %>
      </tr>
      <tr>
        <% unless @profile.address2.blank? %>
        <td><strong>Apt/Suite:</strong></td>
        <td><%= @profile.address2 %></td>
        <% end %>
      </tr>
      <tr>
        <% unless @profile.city.blank? %>
        <td><strong>City:</strong></td>
        <td><%= @profile.city %></td>
         <% end %>
      </tr>
      <tr>
        <% unless @profile.state.blank? %>
        <td><strong>State:</strong></td>
        <td><%= @profile.state %></td>
        <% end %>
      </tr>
      <tr>
        <% unless @profile.zip.blank? %>
        <td><strong>Zip Code:</strong></td>
        <td><%= @profile.zip %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

<div class="step_container modal pop-position">
  <button class="user_exit" id="user_exit">X</button>

<%= render 'users/new', user: @user%>
</div>

<div class="breaker1"></div>

<div class="breaker2"></div>