config/routes.rb
Rails.application.routes.draw do

  root 'profiles#show'
  get '/register' => 'profiles#new'
  post '/register' => 'profiles#show'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # get '/user_form' => 'users#update'
  post '/user_form/:id' => 'users#ajax'
  get '/new_form/:id' => 'users#edit'
  get '/profiles/:id/del' => 'profiles#delivery'
  get '/profiles/:id/orders' => 'profiles#invoice'
  resources :users
  # post '/add_address' => 'profiles#address'

  resources :profiles do
    member do
      get :confirm_email
      put :hold
      get :delivery
      get :invoice
    end

    resources :users
    resources :charges, only: [:create, :update] do
      collection do
        put :cancel
      end
    end
  end


  resources :sessions

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :profile
  has_many :orders
  has_many :products, through: :orders

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :variety, presence: true
  # validates :flow, presence: true
  # validates :scent, presence: true

  def self.birthday_day(birthday)
    birthday.strftime('%B %e %Y')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_profile, only: [:index, :new, :create, :show, :update, :edit, :destroy]
  before_action :set_user, only: [:edit, :update, :show, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = @profile.users.create(user_params)
    if @user.save
      created_product = Product.user_pref(@user)
      Order.create(user_id: @user.id, product_id: created_product.id) rescue nil
      redirect_to profile_path(@profile), notice: "User was successfully created"
    else
      render :new
    end
  end

  def show
  end

  def ajax
    @user = User.find(params[:id])
    @profile = Profile.find(params[:profile_id])
    if request.xhr?
      render '_user',  layout: false
    end
  end

  def edit
    @user = User.find(params[:id])
    @profile = Profile.find(params[:profile_id])
    if request.xhr?
      render '_new',  layout: false
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to profile_path(@profile), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :birthday, :variety, :flow, :scent)
    end

    def set_profile
      @profile = Profile.find(params[:profile_id])
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_ed.html.erb
 <button class="user_exit" id="user_exit">X</button>


     <!-- <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> -->

  <p id="pro_prevent">You must create a user before proceding</p>
  <%= form_for ([@profile, @user]) do |u| %>
  <div>
    <%= u.label :first_name %>
    <%= u.text_field :first_name %>
  </div>
  <div>
    <%= u.label :last_name %>
    <%= u.text_field :last_name %>
  </div>
  <div>
    <%= u.label :birthday %>
    <%= u.date_field :birthday %>
  </div>
    <div class="radio">
      I prefer to use...
      <%= u.radio_button(:variety, "tampon") %>
      <%= u.label(:variety_tampon, "All Tampons") %>
      <%= u.radio_button(:variety, "pad") %>
      <%= u.label(:variety_pad, "All Pads") %>
      <%= u.radio_button(:variety, "combo") %>
      <%= u.label(:variety_combo, "Combination") %>
    </div>
    <div class="radio">
      My flow is...
      <%= u.radio_button(:flow, "light") %>
      <%= u.label(:flow_light, "Light") %>
      <%= u.radio_button(:flow, "medium") %>
      <%= u.label(:flow_medium, "Medium") %>
      <%= u.radio_button(:flow, "heavy") %>
      <%= u.label(:flow_heavy, "Heavy") %>
    </div>
    <div class="radio">
      I prefer my Products: Scented or Unscented?
      <%= u.radio_button(:scent, "scented") %>
      <%= u.label(:scent_scented, "Yes") %>
      <%= u.radio_button(:scent, "unscented") %>
      <%= u.label(:scent_unscented, "No") %>
    </div>
  <%= u.submit %>
 <% end %>

app/views/users/_new.html.erb
<% unless @user.id %>
<p id="pro_prevent" class="flash-message">Thanks for joining TOM! <br> Please set up your box to continue.</p>
<% end %>
  <%= form_for ([@profile, @user]) do |u| %>
  <div>
    <%= u.label :first_name %>
    <%= u.text_field :first_name %>
  </div>
  <div>
    <%= u.label :last_name %>
    <%= u.text_field :last_name %>
  </div>
  <div>
    <%= u.label :birthday %>
    <%= u.date_field :birthday %>
  </div>
  <img src="https://s3.amazonaws.com/tombox/file.png" alt="TomBox" height="50" width="50">
<span class="user-prefq">I want my TOM Box to have: </span>
    <div class="radio">
      <br>
      <%= u.radio_button(:variety, "tampon") %>
      <%= u.label(:variety_tampon, "All Tampons") %>
      <%= u.radio_button(:variety, "pad") %>
      <%= u.label(:variety_pad, "All Pads") %>
      <%= u.radio_button(:variety, "combo") %>
      <%= u.label(:variety_combo, "A Combination") %>
    </div>
    <img src="https://s3.amazonaws.com/tombox/flow-guide.png" alt="TomBox" height="50" width="50">
    <span class="user-prefq">I flow: </span>
    <div class="radio">
      <br>
      <%= u.radio_button(:flow, "light") %>
      <%= u.label(:flow_light, "Light") %>
      <%= u.radio_button(:flow, "medium") %>
      <%= u.label(:flow_medium, "Medium") %>
      <%= u.radio_button(:flow, "heavy") %>
      <%= u.label(:flow_heavy, "Heavy") %>
    </div>
    <img src="https://s3.amazonaws.com/tombox/flower.png" alt="TomBox" height="50" width="50">
    <span class="user-prefq">Do I want scented products? </span>
    <div class="radio">
      <br>
      <%= u.radio_button(:scent, "scented") %>
      <%= u.label(:scent_scented, "Yes") %>
      <%= u.radio_button(:scent, "unscented") %>
      <%= u.label(:scent_unscented, "No") %>
    </div>
    <button class="btn purple darken-1 waves-effect waves-light" type="submit" name="action" id='create_user'>  <%= u.submit %>
    </button>

 <% end %>

app/views/users/_user.html.erb
  <p class="dis_title"><%= @user.first_name%>'s Tom Box</p>
  <table class="responsive-table bordered">
    <tbody>
      <tr>
        <td class="header"><strong>First Name:</strong></td>
        <td class="info"><%= @user.first_name %></td>
      </tr>
      <tr>
        <td><strong>Last Name:</strong></td>
        <td class="info"><%= @user.last_name %></td>
      </tr>
      <tr>
        <td><strong>Birthday:</strong></td>
        <td class="info"><%= User.birthday_day(@user.birthday) %></td>
      </tr>
      <tr>
        <td><strong>My Products </strong></td>
        <td><%= @user.variety %></td>
      </tr>
      <tr>
        <td><strong>My Flow </strong></td>
        <td><%= @user.flow %></td>
      </tr>
      <tr>
        <td><strong>I like my products to be </strong></td>
        <td><%= @user.scent %></td>
      </tr>
    </tbody>
  </table>
  <br><br>
  <button style="z-index:0;"class="btn purple darken-1 waves-effect waves-light" type="submit" name="action"><%= button_to "Edit User", edit_profile_user_path(@profile.id, @user.id), id: "user_edit" %>
  </button>

  <button style="z-index:0;" class="btn purple darken-1 waves-effect waves-light" type="submit" name="action"><%= button_to "Remove User", profile_user_path(params[:profile_id], @user), method: "delete" %>
  </button>

app/views/users/edit.html.erb
<h5>Update Your Box </h5>
<%= render 'new', user: @user%>

app/views/users/new.html.erb
<h1>new user</h1>

<%= render 'new', user: @user%>

app/views/users/show.html.erb
<div> NOT THE PAGE
  <strong><%= @user.first_name%>TOM Box </strong>
  <br>
  <strong>First Name:</strong>
  <%= @user.first_name %>
  <br>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
  <br>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
  <br>
  <strong>My Box: <%= @user.flow %> <%= @user.scent %> <%= @user.variety %></strong>


  <!-- <%= @user.variety %>
  <br>
  <strong>Flow</strong>
  <%= @user.flow %>
  <br>
  <strong>Scented?</strong>
  <%= @user.scent %>
</div>
<br>
<br> -->


<!-- # <%= link_to 'Edit', edit_profile_user_path(@profile, @user) %> | -->
<%= link_to 'Add Another Box', new_profile_user_path(@profile) %> |

<!-- <%#= link_to 'Cancel these preferences', destroy_user_path(@profile) %> | -->

<%= link_to 'delivery_profile_path', @profile %>
<!-- <h3> should be go to Delivery/checkout" </h3> -->