config/routes.rb
Rails.application.routes.draw do

  root 'profiles#show'
  get '/register' => 'profiles#new'
  post '/register' => 'profiles#show'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # get '/user_form' => 'users#update'
  post '/user_form/:id' => 'users#ajax'
  get '/new_form/:id' => 'users#edit'
  get '/profiles/:id/del' => 'profiles#delivery'
  get '/profiles/:id/orders' => 'profiles#invoice'
  resources :users
  # post '/add_address' => 'profiles#address'

  resources :profiles do
    member do
      get :confirm_email
      put :hold
      get :delivery
      get :invoice
    end

    resources :users
    resources :charges, only: [:create, :update] do
      collection do
        put :cancel
      end
    end
  end


  resources :sessions

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

skip_before_filter  :verify_authenticity_token


  def index
  end

  def new
  end

  def create
    @profile = Profile.find(params[:profile_id])

    token = params[:stripeToken]

    customer = Stripe::Customer.create(
      :email => @profile.email,
      :source  => token,
      :plan => "TOM",
      :quantity => @profile.users.count
      )
      @profile.subscribed = true
      @profile.stripe_id = customer.id
      @profile.card_token = customer.default_source
      @profile.Subscription_id = customer.subscriptions.data[0].id
      @profile.save!
      redirect_to profile_path(@profile)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end

 def update
   @profile = Profile.find(params[:profile_id])

  customer = Stripe::Customer.retrieve(@profile.stripe_id)
    customer.quantity = @profile.users.count
    customer.source = @profile.card_token
    customer.email = @profile.email
    customer.save!

   redirect_to profile_path(@profile)

end

  def show
    @profile = Profile.find(params[:profile_id])
  Stripe::Customer.retrieve(@profile.stripe_id)
  end

  def cancel
    @profile = Profile.find(params[:profile_id])

    if @profile.subscribed == true
      @profile.update(subscribed: false)
    else
      @profile.update(subscribed: true)
    end
    @profile.save

    cu = Stripe::Customer.retrieve(@profile.stripe_id)
    cu.delete
      redirect_to profile_path(@profile)
  end

def plan_create
  plan = Stripe::Plan.create(
  :id       => 'TOM',
  :amount   => 900,
  :currency => 'usd',
  :interval => 'month',
  :name     =>  'TOM Monthly Box',
  :statement_descriptor => "TOM Box Subscription"
  )
end
  #
  # def buildJWT(secret, userId, accountId, email, firstName, lastName, referralCode, userReferralCode, accountStatus, userImage, expiryDate)
  #     secret = 'Referral SaaSquatch API key'
  #     return payload = JWT.encode({
  #     user: {
  #     id: userId,
  #     accountId: accountId,
  #     firstName: firstName,
  #     lastName: lastName,
  #     referralCode: referralCode,
  #     userReferralCode: userReferralCode,
  #     accountStatus: accountStatus,
  #     userImage: userImage
  #     },
  #     exp: expiryDate #optional date in seconds since the epoch
  #     }, secret)
  # end


end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_custom.html.erb
<form action="<%= profile_charges_path(@profile) %>" method="POST" id="payment-form">
  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number">
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YY)</span>
      <input type="text" size="2" data-stripe="exp_month">
    </label>
    <span> / </span>
    <input type="text" size="2" data-stripe="exp_year">
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc">
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Billing Zip</span>
      <input type="text" size="6" data-stripe="address_zip">
    </label>
  </div>

  <input type="submit" class="submit" value="Submit Payment">
</form>

app/views/charges/_new.html.erb
<form action="<%= profile_charges_path(@profile) %>" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key= '<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>'
    data-amount="Subscribe"
    data-name="TOM BOX"
    data-description="TOM monthly Subscription"
    data-image="https://s3.amazonaws.com/tombox/Screen+Shot+2016-08-09+at+12.41.00+PM.png"
    data-locale="auto"
    data-zip-code="true">
  </script>
</form>

app/views/charges/create.html.erb
<h1>confirmation </h1>
<h2> You have subscribd to TOM"</h2>

<h2> Show refferal code  on this page? </h2>

<%= link_to 'Profile Show Page', profile_path(@profile) %>






<!-- <button class="squatchpop">Referral Discount></button>


<script type="text/javascript">
  var _sqh = _sqh || [];

  _sqh.push(['init', {
     tenant_alias: 'test_ao1a2qmlvdugs',
     account_id: '10',
     payment_provider_id: '<%= @profile.stripe_id %>',
     user_id: '10',
     email: 'laleibo@gmail.com',
     first_name: 'lauren',
     last_name: 'Leibowitz'
  }]);

    (function(){function l(){var s=document.createElement("script");s.type="text/javascript";s.async=true;s.src=location.protocol+"//d2rcp9ak152ke1.cloudfront.net/assets/javascripts/squatch.min.js";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t)}if(window.attachEvent){window.attachEvent("onload",l)}else{window.addEventListener("load",l,false)}})();
</script> -->